### PR TITLE
[IOS-4436] Adding a property to the MediationSettings to check if the muted flag was set by the publisher.

### PR DESCRIPTION
**Pull request by stanley-vungle**
Adding a property to the MediationSettings to check if the muted flag was set by the publisher.

IOS-4436

### CODE REVIEW

**Review by crbinsf — COMMENTED** [review]
Changes look ok - just one question for clarification - in this fix, does the one property found in the instance mediation settings for muted apply to all placements?  How would a publisher specify that only certain placements should start muted?

**Comment by stanley-vungle** [comment]
@crbinsf 
> in this fix, does the one property found in the instance mediation settings for muted apply to all placements?

The mediation settings are applied only for the rewarded ad unit that is being loaded. It does not affect any other rewarded ad units if it is not loaded with the settings.

> How would a publisher specify that only certain placements should start muted?

The publisher would supply the mediation settings to the specific rewarded ad units to be muted during the load call. And not supply any or with a different value for the other placements.


A note is that the QA test app doesn't have the design currently to decide whether to apply the mediation settings or not. It always applies some type of settings object.

**Comment by crbinsf** [comment]
@stanley-vungle thanks for the explanation - just wanted to be sure I understood how the fix would be utilized here.

**Review by crbinsf — APPROVED** [review]
LGTM

**Review by crbinsf — APPROVED** [review]

**Review by ManojBudumuru-vungle — APPROVED** [review]
LGTM

**Review by ashinagawa — APPROVED** [review]
LGTM

**Pull request merged**
